services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    networks:
      - vite_node_network
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    networks:
      - vite_node_network
networks:
  vite_node_network:
    driver: bridge
